accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    # path('<int:pk>/delete/', views.delete, name='delete'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.change_password, name='change_password'),
    path('<int:user_id>/profile/', views.profile, name='profile'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update', views.update, name='update'),
    path('<int:article_pk>/comment', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comment/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/like', views.like, name='like'),
    path('<int:hash_pk>/hashtag/', views.hashtag, name='hashtag'),
    # path('hashtags/', views.popular_tag, name='popular_tag'),
    path('make_cloud/', views.make_cloud, name='make_cloud'),
    path('popular_tags/', views.popular_tags, name='popular_tags'),
]

carrot_shake/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('questions/', include('questions.urls')),
    path('accounts/', include('allauth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/urls.py
from django.urls import path
from . import views


app_name = 'questions'

urlpatterns = [
    path('', views.indexing, name='indexing'),
    path('write/', views.write, name='write'),
    path('<int:question_pk>/detailing/', views.detailing, name='detailing'),
    path('<int:question_pk>/deleting/', views.deleting, name='deleting'),
    # path('<int:question_pk>/update', views.update, name='update'),
]

questions/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Question(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    
    title = models.CharField(max_length=10)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

questions/forms.py
from django import forms
from .models import Question


class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ('title', 'content',)

questions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_http_methods, require_safe
from django.contrib.auth.decorators import login_required
from .models import Question
from .forms import QuestionForm

@require_safe
def indexing(request):
    questions = Question.objects.all()
    context = {
        'questions': questions,
    }
    return render(request, 'questions/indexing.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def write(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.user = request.user
            question.save()
            return redirect('questions:indexing')
    else:
        form = QuestionForm()
    context = {
        'form': form,
    }
    return render(request, 'questions/write.html', context)


@require_POST
def deleting(request, question_pk):
    question = get_object_or_404(Question, pk=question_pk)
    if request.user == question.user:
        question.delete()
        return redirect('questions:indexing')
    return redirect('questions:detailing', question_pk)


@require_safe
def detailing(request, question_pk):
    question = get_object_or_404(Question, pk=question_pk)
    context = {
        'question': question,
    }
    return render(request, 'questions/detailing.html', context)

questions/templates/questions/detailing.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>세부사항</h1>
  <hr>
  <p>작성자: {{ question.user }}</p>
  <h3>제목: {{ question.title }}</h3>
  <br>
  <p>내용 : {{ question.content }}</p>
  <br>
  <hr>

  {% if request.user == question.user %}
    <div class="d-inline">
      {% comment %} <a href="{% url 'articles:update' article.pk %}"><button class="btn btn-info">수정하기</button></a> {% endcomment %}
      <form action="{% url 'questions:deleting' question.pk %}" method="POST">
        {% csrf_token %}
        <button class="btn btn-danger">삭제</button>
      </form>
    </div>
  {% endif %}

  <a href="{% url 'questions:indexing' %}">뒤로가기</a>
{% endblock content %}

questions/templates/questions/indexing.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center my-4">문의사항</h1>
  <br>
  <a href="{% url 'questions:write' %}"><button class="btn btn-light">새 글 작성하기</button></a>

  <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">작성자</th>
      <th scope="col">제목</th>
    </tr>
  </thead>
  {% for question in questions %}
  <tbody>
    <tr>
      <th scope="row">{{ question.pk }}</th>
      <td>{{ question.user }}</td>
      <td><a href="{% url 'questions:detailing' question.pk %}">{{ question.title }}</a></td>
    </tr>
  </tbody>
  {% endfor %}
</table> 

{% endblock content %}

questions/templates/questions/write.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>새 글 작성</h1>
  <form action="{% url 'questions:write' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <br>
    <button class="btn btn-warning">제출</button>
    <br>
    <br>
  </form>
{% endblock content %}