accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    # path('<int:pk>/delete/', views.delete, name='delete'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.change_password, name='change_password'),
    path('<int:user_id>/profile/', views.profile, name='profile'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update', views.update, name='update'),
    path('<int:article_pk>/comment', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comment/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/like', views.like, name='like'),
    path('<int:hash_pk>/hashtag/', views.hashtag, name='hashtag'),
    # path('hashtags/', views.popular_tag, name='popular_tag'),
    path('make_cloud/', views.make_cloud, name='make_cloud'),
    path('popular_tags/', views.popular_tags, name='popular_tags'),
]

carrot_shake/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('questions/', include('questions.urls')),
    path('accounts/', include('allauth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')
    profile_image = models.ImageField(blank=True)

articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, Transpose

# Create your models here.

class Hashtag(models.Model):
    content = models.TextField(unique=True)
    # article_cnt = models.IntegerField(default = 1) # 0을 기본 

    def __str__(self):
        return self.content

        
class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    hashtags = models.ManyToManyField(Hashtag)
    title = models.CharField(max_length=10)
    content = models.TextField()
    image = models.ImageField(blank=True)
    image_thumbnail_detail = ImageSpecField(source='image',
                                     processors=[
                                         #  이미지 회전 방지
                                         Transpose(),
                                         ResizeToFill(670, 500)
                                         ],
                                     format='JPEG',
                                     options={'quality': 100})
    image_thumbnail_index = ImageSpecField(source='image',
                                     processors=[
                                        #  이미지 회전 방지
                                         Transpose(),
                                         ResizeToFill(200, 200)
                                         ],
                                     format='JPEG',
                                     options={'quality': 100})
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    price = models.IntegerField()


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True)

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields


class CustomUserChangeForm(UserChangeForm):
    
    class Meta():
        model = get_user_model()
        fields = ('username', 'email', 'profile_image',)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.views.decorators.http import require_POST, require_http_methods
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, CustomUserChangeForm


# Create your views here.
@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        redirect('articles:index')

    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('articles:index')


@require_http_methods(['GET', 'POST'])
def signup(request):
    if request.user.is_authenticated:
        redirect('articles:index')

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile', request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@require_POST
def delete(request):
    # user = get_object_or_404(get_user_model(), pk=pk)
    # user.delete()
    if request.method == 'POST':
        request.user.delete()
        auth_logout(request)
    return redirect('articles:index')


@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


def profile(request, user_id):
    person = get_object_or_404(get_user_model(), pk=user_id)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)


def follow(request, user_id):
    if request.user.is_authenticated:
        person = get_object_or_404(get_user_model(), pk=user_id)
        if request.user != person:
            if request.user in person.followers.all():
                person.followers.remove(request.user)
            else:
                person.followers.add(request.user)
        return redirect('accounts:profile', person.pk)
    return redirect('accounts:login')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
  <h1>Change_Password</h1>
  <br>
  <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary">Change_Password</button>
  </form>
  <br>
  <a href="{% url 'articles:index' %}">BACK</a>
{% endblock  %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load socialaccount %}

{% block content %}
  <h1>Login</h1>
  <br>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <br>
    <button class="btn btn-primary">Login</button>
  </form>
  <br>
  <a href="{% provider_login_url "google" next="/articles/" %}">Google</a><br>
  <a href="{% url 'articles:index' %}">BACK</a>
{% endblock  %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="d-flex justify-content-around" style="margin-top: 30px; margin-bottom: 30px;">
  {# 프로필 사진 #}
  <div style="width: 150px; height: 150px;">
    {% if person.profile_image %}
      <img style="width: 100%; height: 100%;" src="{{ person.profile_image.url }}" alt="profile image">
    {% else %}
      <img style="width: 100%; height: 100%;" src="{% static 'images/profile_rabbit.png' %}" alt="profile image">
    {% endif %}
  </div>
  <div>
    {# 이름, 설정버튼 #}
    <span class="h3" style="margin-right: 15px; margin-bottom: 40px;">{{ person.username }}'s Profile</span>
    {% if request.user == person %}
    <span class="dropdown">
      <a href="#" role="button" data-bs-toggle="dropdown">
        <i class="fas fa-cog"></i>
      </a>
      <ul class="dropdown-menu">
      <li><a class="dropdown-item" href="{% url 'accounts:update' %}">Update info</a></li>
      <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
      </ul>
    </span>
    {% endif %}
    {# 게시글, 팔로워, 팔로잉 수 #}
    <ul class="my-3">
      <li style="float: left; margin-right: 15px;">
        <span>followers</span>
        {{ person.followers.all|length }}
      </li>
      <li style="margin-right: 15px;">
        <span>followings</span>
        {{ person.followings.all|length }}
      </li>
      <li>
        <span>작성글</span>
        {{ person.article_set.all|length }}
      </li>
    </ul>
    {# 팔로우 버튼 #}
    {% if request.user.is_authenticated %}
      <form action="{% url 'accounts:follow' person.pk %}" method="POST">
      {% csrf_token %}
      {% if request.user != person %}
        {% if request.user in person.followers.all %}
          <button class="btn btn-outline-secondary btn-sm">[UnFollow]</button>
        {% else %}
          <button class="btn btn-outline-secondary btn-sm">[Follow]</button>
        {% endif %}
      {% endif %}
      </form>
    {% endif %}
  </div>
</div>
<hr>
{# 게시물 #}
<div class="d-flex justify-content-start flex-wrap">
  {% for article in person.article_set.all %}
    {% if article.image %}
      <div class="m-3">
        <a href="{% url 'articles:detail' article.pk %}">
          {% comment %} <img style="width: 300px; height: 300px;" src="{{ article.image.url }}" alt="{{ article.image }}"> {% endcomment %}
          {% comment %} <div class="fw-bold d-flex justify-content-center mb-1">{{ article.title }}</div> {% endcomment %}
          <img class="mb-2" src="{{ article.image_thumbnail_index.url }}" alt="{{ article.image_thumbnail_index }}">
        </a>
        <div class="d-flex justify-content-center">
          <span style="margin-right: 10px;"><i class="fas fa-heart" style="color: crimson;"></i> {{ article.like_users.all|length }}</span>
          <span><i class="far fa-comment" style="color: blue;"></i> {{ article.comment_set.all|length }}</span>
        </div>
      </div>
    {% else %}
    <div class="m-3 d-flex align-items-center">
      <a href="{% url 'articles:detail' article.pk %}">
        <span class="fw-bold d-flex justify-content-center mb-1">{{ article.title }}</span>
      </a>
    </div>
    {% endif %}
    
  {% endfor %}
</div>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1>Signup</h1>
  <br>
  <form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <br>
    <button class="btn btn-primary">Signup</button>
  </form>
  <br>
  <a href="{% url 'articles:index' %}">BACK</a>
{% endblock  %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
  <h1>Update</h1>
  <br>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary">Update</button>
  </form>
  <br>
  <a href="{% url 'articles:index' %}">BACK</a>
{% endblock  %}