accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    # path('<int:pk>/delete/', views.delete, name='delete'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.change_password, name='change_password'),
    path('<int:user_id>/profile/', views.profile, name='profile'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update', views.update, name='update'),
    path('<int:article_pk>/comment', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comment/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/like', views.like, name='like'),
    path('<int:hash_pk>/hashtag/', views.hashtag, name='hashtag'),
    # path('hashtags/', views.popular_tag, name='popular_tag'),
    path('make_cloud/', views.make_cloud, name='make_cloud'),
    path('popular_tags/', views.popular_tags, name='popular_tags'),
]

carrot_shake/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('questions/', include('questions.urls')),
    path('accounts/', include('allauth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

questions/urls.py
from django.urls import path
from . import views


app_name = 'questions'

urlpatterns = [
    path('', views.indexing, name='indexing'),
    path('write/', views.write, name='write'),
    path('<int:question_pk>/detailing/', views.detailing, name='detailing'),
    path('<int:question_pk>/deleting/', views.deleting, name='deleting'),
    # path('<int:question_pk>/update', views.update, name='update'),
]

carrot_shake/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <!--구글 폰트-->
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Noto+Serif+KR&display=swap" rel="stylesheet"> 
  <title>Rabbit Market</title>
  <style>
    body {
        font-family: 'Noto Serif KR', serif;
        margin-bottom: 50px;
        margin-top: 45px;
      }

    a:hover {
      font-weight: bold;
    }
    a {
      color: black;
      text-decoration: none;
    }
    .btn {
      text-decoration: none;
      color: black;
    }
    .btn:hover {
      font-weight: bold;
    }

    .carousel-item img{
      height: 300px;
      width: 1000px;
    }
    {% comment %} 네브바 색 준거 다시 흰색으로 원위치 {% endcomment %}
    .container-fluid {
      background-color: #fba8c1;
    }

    .form-control {
      border: 1px solid #a2cde5;
      box-shadow: 0 0 0 0.2rem rgba(162, 205, 229, 0.25);
    }

    ul {
      list-style: none;
      padding-left: 0px;
    }
    {% comment %} articles의 css가 먹히지 않아서 사용 - detail 클래스 {% endcomment %}
    .nickname {
    font-size: 15px;
    font-weight: 600;
    line-height: 1.5;
    letter-spacing: -0.6px;
    color: #212529;
    margin-top: 25px;
    padding-bottom: 23px;
    }

    .article-title {
      font-size: 20px;
      font-weight: 600;
      line-height: 1.5;
      letter-spacing: -0.6px;
    }

    .article-hashtag {
      margin-top: 4px;
      font-size: 13px;
      line-height: 1.46;
      letter-spacing: -0.6px;
      color: #868e96;
    }
    
  </style>
</head>

<body> 
  <nav class="navbar navbar-expand-lg navbar-light">
    <div class="container-fluid fixed-top bg-light">

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ms-4">
          {# login 된 사용자의 경우#}
          {% if request.user.is_authenticated %}
            <a class="nav-link text-dark" href="{% url 'accounts:profile' user.pk %}">{{ request.user }}</a>
            <a class="nav-link text-dark" href="{% url 'articles:index' %}"><i class="fas fa-home fa-lg"></i></a>
            <a class="nav-link text-dark" href="{% url 'articles:create' %}"><i class="far fa-plus-square fa-lg"></i></a>
            {% comment %} <a class="nav-link text-dark" href="{% url 'accounts:update' %}">User:Update</a> {% endcomment %}
            <form action="{% url 'accounts:logout' %}" method="POST">
              {% csrf_token %}
              <button class="btn btn-link text-decoration-none text-dark">Logout</button>
            </form>
          {# 익명 유저 #}
          {% else %}
            <a class="navbar-brand" href="{% url 'articles:index' %}">Guest</a>
            <a class="nav-link text-dark" href="{% url 'accounts:login' %}">Login</a>
            <a class="nav-link text-dark" href="{% url 'accounts:signup' %}">Signup</a>
          {% endif %}
        </div>
      </div>
    </div>
  </nav>
  {# carousel 이미지 #}
  <div class="container">
    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="{% static 'images/rabbitpic3.jpg' %}"class="d-block w-100" alt="image">
        </div>
        <div class="carousel-item">
          <img src="{% static 'images/rabbitpic.jpg' %}"class="d-block w-100" alt="rabbit1">
        </div>
        <div class="carousel-item">
          <img src="{% static 'images/rabbitpic2.jpg' %}"class="d-block w-100" alt="rabbit2">
        </div>
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
  </div>

  <div class="container">
    {% block content %}{% endblock content %}
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/04f66c8c42.js" crossorigin="anonymous"></script>
</body>

<div class="container">
  <footer class="w3-row-padding w3-padding-32">
    <hr style="border-top: 1px solid #bbb;">  
    <div class="w3-third">
      <h3>FOOTER</h3>
      <p>© 2021 Rabbit Inc. All rights reserved.</p>
      <p>Design by <a href="https://github.com/ssw02238/CarrotPjt" target="_blank" rel="nofollow">은총은지윤서</p></a>
    </div>
  
    <div class="w3-third">
    <a href="{% url 'articles:index' %}">
      <img src="{% static 'images/하단이미지.jpg' %}" alt="image_below" style='width:250px;'>
    </a>
    </div>
    <div class="w3-third">
      <h3>Link</h3>
      <ul class="w3-ul w3-hoverable">
        <li class="w3-padding-16">
          <a href="{% url 'articles:popular_tags' %}"><button class="btn btn-outline-danger">CHECK</button></a>
          <span> 유행하는 아이템 확인하기! </span>
            
        </li>
        <li class="w3-padding-16">
        <a href="{% url 'questions:indexing' %}">
            <img src="{% static 'images/1rabbit.jpg' %}" class="w3-left w3-margin-right" style="width:80px;height: 40px;">
            <span class="w3-large">Sending</span><br>
            <span>언제든지 문의해주세요 </span>
        </a>
        </li> 
      </ul>
    </div>
    </div>
  </footer>
</div>
</html>