accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    # path('<int:pk>/delete/', views.delete, name='delete'),
    path('delete/', views.delete, name='delete'),
    path('password/', views.change_password, name='change_password'),
    path('<int:user_id>/profile/', views.profile, name='profile'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update', views.update, name='update'),
    path('<int:article_pk>/comment', views.comment_create, name='comment_create'),
    path('<int:article_pk>/comment/<int:comment_pk>/delete', views.comment_delete, name='comment_delete'),
    path('<int:article_pk>/like', views.like, name='like'),
    path('<int:hash_pk>/hashtag/', views.hashtag, name='hashtag'),
    # path('hashtags/', views.popular_tag, name='popular_tag'),
    path('make_cloud/', views.make_cloud, name='make_cloud'),
    path('popular_tags/', views.popular_tags, name='popular_tags'),
]

carrot_shake/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('questions/', include('questions.urls')),
    path('accounts/', include('allauth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.conf import settings
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, Transpose

# Create your models here.

class Hashtag(models.Model):
    content = models.TextField(unique=True)
    # article_cnt = models.IntegerField(default = 1) # 0을 기본 

    def __str__(self):
        return self.content

        
class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    hashtags = models.ManyToManyField(Hashtag)
    title = models.CharField(max_length=10)
    content = models.TextField()
    image = models.ImageField(blank=True)
    image_thumbnail_detail = ImageSpecField(source='image',
                                     processors=[
                                         #  이미지 회전 방지
                                         Transpose(),
                                         ResizeToFill(670, 500)
                                         ],
                                     format='JPEG',
                                     options={'quality': 100})
    image_thumbnail_index = ImageSpecField(source='image',
                                     processors=[
                                        #  이미지 회전 방지
                                         Transpose(),
                                         ResizeToFill(200, 200)
                                         ],
                                     format='JPEG',
                                     options={'quality': 100})
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    price = models.IntegerField()


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    # updated_at = models.DateTimeField(auto_now=True)

articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    title = forms.CharField(
        label='',
        # required = False, 
        widget=forms.TextInput(
            attrs={
                'placeholder': '제목',
                'maxlength': 10,
                # 'required': False, # 안됨...
            }
        ),
         error_messages={
            'required': '제목이 유효하지 않습니다.',
        }
    )

    price = forms.IntegerField(
        label='',
        widget=forms.TextInput(
            attrs={
                'placeholder': '가격',
                # 'required': False,
            }
        ),
        error_messages={
            'required': '가격이 유효하지 않습니다.',
        }
    )

    content = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={
                'placeholder': '내용',
                # 'required': False,
            }
        ),
        error_messages={
            'required': '내용이 유효하지 않습니다.',
        }
    )

    class Meta:
        model = Article
        fields = ('title', 'price', 'content', 'image',)


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = ('user', 'article',)

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST, require_http_methods, require_safe
from django.contrib.auth.decorators import login_required
from django.conf import settings
from wordcloud import WordCloud, STOPWORDS
from .models import Article, Comment, Hashtag
from .forms import ArticleForm, CommentForm
# from django.core.paginator import Paginator
from django.db.models import Count

# Create your views here.
@require_safe
def index(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            # hashtag
            for word in article.content.split(): # content 를 공백기준으로 리스트로 변경
                if word[0] == '#': # '#'로 시작하는 요소 선택
                    hashtag, created = Hashtag.objects.get_or_create(content=word) # word(content안에 해시태그)랑 같은 기존 해시태그를 찾으면 기존 객체를, 없으면 새로운 객체를 return
                    article.hashtags.add(hashtag)
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/create.html', context)


@require_safe
def detail(request, article_pk):
    article = Article.objects.get(pk=article_pk)
    comment_form = CommentForm()
    comments = article.comment_set.all()
    hashtags = article.hashtags.all()
    context = {
        'article': article,
        'comments': comments,
        'comment_form': comment_form,
        'hashtags': hashtags,
    }
    return render(request, 'articles/detail.html', context)


@require_POST
def delete(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user == article.user:
        article.delete()
        return redirect('articles:index')
    return redirect('articles:detail', article_pk)
    

@login_required
@require_http_methods(['GET', 'POST'])
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                form.save()
                article.hashtags.clear() # 해당 article 의 hashtag 전체 삭제
                for word in article.content.split():
                    if word[0] == '#':
                        hashtag, created = Hashtag.objects.get_or_create(content=word)
                        article.hashtags.add(hashtag)
                return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:detail', article_pk)    
    context = {
        'form': form,
        'article': article,
    }
    return render(request, 'articles/update.html', context)


def comment_create(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.article = article 
            comment.save()
            return redirect('articles:detail', article_pk)
        context = {
            'article': article,
            'comment_form': comment_form,
        }
        return render(request, 'articles/detail.html', context)
    return redirect('accounts:login')


def comment_delete(request, article_pk, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('articles:detail', article_pk)


def like(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user in article.like_users.all():
        # 하트 취소 
        article.like_users.remove(request.user)
    else:
        article.like_users.add(request.user)
    return redirect('articles:detail', article_pk)


def hashtag(request, hash_pk):
    hashtag = get_object_or_404(Hashtag, pk=hash_pk)
    articles = hashtag.article_set.order_by('-pk')
    context = {
        'hashtag': hashtag, 
        'articles': articles,
    }
    return render(request, 'articles/hashtag.html', context)
   

def make_cloud(request):
    # 전체 해시태그 받아오기
    hashtags = Hashtag.objects.all()
    text = ''.join([str(i) for i in hashtags])
    # stopwords
    stopwords = set(STOPWORDS)
    stopwords.add('#')
    # 이미지 만들기
    wc = WordCloud(stopwords=stopwords).generate(text)
    image = wc.to_image()
    # PIL 파일을 jpeg 파일로 바꿔서 static 폴더에 저장하기
    image.save(str(settings.STATICFILES_DIRS[2]) + '/articles/cloud.jpeg')
    return render(request, 'articles/wordcloud.html')

def popular_tags(request):
    # rank 확인용
    hashtags = Hashtag.objects.annotate(
        total_article = Count('article')
    ).order_by('-total_article')[:3]

    context = {
        'hashtags': hashtags,
    }
    return render(request, 'articles/popular_tag.html', context)

articles/templates/articles/_card.html
{% load static %}
<link rel="stylesheet" href="{% static 'articles/style.css' %}">

<div class="card h-100" style="width: 18rem;">
  <a href="{% url 'articles:detail' article.pk %}">
    {% if article.image %}
      <img src="{{ article.image_thumbnail_index.url }}" class="card-img-top img-thumbnail" alt="{{ article.image }}">
    {% endif %}

    <div class="card-body">
      <h2 class="card-title" style="font-family: 'Noto Serif KR', serif;">{{ article.title }}</h2>
      <p class="card-price">{{ article.price }}원</p>
      <div class="card-counts">
        <span>관심 {{ article.like_users.all|length }}</span>
        ∙
        <span>댓글 {{ article.comment_set.all|length }}</span>
      </div>
    </div>
  </a>
</div>

articles/templates/articles/create.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1 class="my-4">새 거래 글쓰기</h1>
  <form action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <br>
    <button class="btn btn-warning">제출</button>
    <br>
    <br>
  </form>
{% endblock content %}

articles/templates/articles/detail.html
{% extends 'base.html' %}
{% load make_hashtag_link %}
{% load bootstrap5 %}
{% load static %}

{% block content %}
{% comment %} 이미지 {% endcomment %}
  <div class="my-5">
    {% if article.image %}
      <div class="d-flex justify-content-center">
        <img src="{{ article.image_thumbnail_detail.url }}" alt="{{ article.image_thumbnail_detail }}" class="img-fluid">
      </div>
    {% endif %}
  </div>

  {% comment %} 프로필 {% endcomment %}
  <a href="{% url 'accounts:profile' article.user.pk %}" class="nickname">
    <div class="d-flex justify-content-start">
      <div style="width: 40px; height: 40px;">
        {% if article.user.profile_image %}
          <span>
            <img style="width: 100%; height: 100%;" src="{{ article.user.profile_image.url }}" alt="profile image">
          </span>
        {% else %}
          <span>
            <img style="width: 100%; height: 100%;" src="{% static 'images/profile_rabbit.png' %}" alt="profile image">
          </span>
        {% endif %}
      </div>
      <span class="ms-3 d-flex align-items-center fw-bold">{{ article.user }}</span>
    </div>
  </a>
  
  <hr>
  {% comment %} 글 내용 {% endcomment %}
  <h1 class="article-title" style="font-family: 'Noto Serif KR', serif;">{{ article.title }} ({{ article.comment_set.all|length }})</h1>
  <div class="article-hashtag">
    {% for hashtag in hashtags %}
      <span ><a href="{% url 'articles:hashtag' hashtag.pk %}" style="color: #868e96;">{{ hashtag }}</a></span>
    {% endfor %}
    <p>{{ article.updated_at }}</p>
  </div>
  <div style="font-size: 18px;font-weight: bold;">{{ article.price }}원</div>
  <br>
  <p>{{ article|hashtag_link|safe }}</p>
  <p style="color: #868e96;font-size: 13px;">관심 {{ article.like_users.all|length }} ∙ 댓글 {{ article.comment_set.all|length }}</p>
  <hr>
  {% comment %} 좋아요, 몇 명 좋아요 {% endcomment %}
  <form action="{% url 'articles:like' article.pk %}" method="POST">
    {% csrf_token %}
    {% if request.user in article.like_users.all %}
      <button class="btn btn-link"><i class="fas fa-heart fa-2x" style="color:crimson;"></i></button>
    {% else %}
      <button class="btn btn-link"><i class="far fa-heart fa-2x" style="color:crimson;"></i></button>
    {% endif %}
    {{ article.like_users.all|length }}명이 좋아합니다.
  </form>
  {% comment %} 수정, 삭제 {% endcomment %}
  {% if request.user == article.user %}
    <div class="my-3">
      <a href="{% url 'articles:update' article.pk %}"><button class="btn btn-outline-secondary btn-sm">수정</button></a>
      <form action="{% url 'articles:delete' article.pk %}" method="POST" class="d-inline">
        {% csrf_token %}
        <button class="btn btn-outline-danger btn-sm">삭제</button>
      </form>
    </div>
  {% endif %}

  {% comment %} 코멘트 {% endcomment %}
  <form action="{% url 'articles:comment_create' article.pk %}" method="POST" class="mt-5">
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    <button class="btn btn-outline-secondary mb-4">제출</button>
  </form>
  <ul>
    {% for comment in comments %}
      <div>
        <li class="my-2 me-4 d-inline-block">
          <div class="fw-bold">{{ comment.user }}</div>
          <div>{{ comment.content }}</div>
          <div style="font-size: 11px; color: #868e96;">{{ comment.created_at }}</div>
        </li>
        <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" class="d-inline">
          {% csrf_token %}
          <button class="btn btn-link"><i class="fas fa-trash-alt"></i></button>
        </form>
      </div>
    {% endfor %}
  </ul>
  <a href="{% url 'articles:index' %}">뒤로가기</a>
{% endblock content %}

articles/templates/articles/hashtag.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ hashtag.content }}</h1>
  <p>{{ articles|length }}개의 게시글이 {{ hashtag.content }}를 태그중입니다.</p>
  
  <hr>

  <h2>{{ hashtag.content }}를 태그한 게시글</h2>
  {% for article in articles %}
    <p>제목 : {{ article.title }}</p>
    <a href="{% url 'articles:detail' article.pk %}">보러가기</a>
    <hr>
  {% endfor %}
{% endblock %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1 class="text-center my-5" style="font-family: 'Noto Serif KR', serif;">지금 올라오는 매물</h1>
  <div class="d-flex justify-content-end">
    <form action="{% url 'articles:make_cloud' %}">
      <button class="btn btn-outline-primary">View Hashtag Cloud</button>
    </form>
  </div>
  <br>
  <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 row-cols-xl-4 g-3">
    {% for article in articles %}
      <div class="col">
        {% include 'articles/_card.html' with article=article %}
      </div>
    {% endfor %}
  </div>
{% endblock content %}

articles/templates/articles/popular_tag.html
{% extends 'base.html' %}

{% block content %}
<br>
<h1>Popular tag</h1>
<p style='color:purple;'>가장 HOT한 매물을 확인해보세요!</p>
<i class="bi bi-arrow-down"></i>
<hr>
  <table class="table table-light" style="width: 200px" >
        <thead>
          <tr class="table-info">
            <th scope="col" >Rank</th>
            <th scope="col" >Hashtag</th>
            <th scope="col" >Count</th>

          </tr>
        </thead>
        {% for hash in hashtags %}
        <tbody>
        <div>
          <tr>
            <td>{{ hash.id }}</td>
            <td><a href="http://127.0.0.1:8000/articles/{{ hash.pk }}/hashtag/">{{ hash.content }}</td></a>
            <td>{{ hash.total_article }}</td>
          </tr> 
          </div>
        </tbody>
        {% endfor %}     
      </table> 
{% endblock content %}

articles/templates/articles/update.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block content %}
  <h1 class="my-4">수정</h1>
  <form action="{% url 'articles:update' article.pk %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}
    <br>
    <button class="btn btn-warning">제출</button>
    <br>
    <br>
  </form>
{% endblock content %}

articles/templates/articles/wordcloud.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <h2>Popular Hashtags</h2>
  <div class="container">
    <img src="{% static 'articles/cloud.jpeg' %}" alt="cloud"> 
  </div>
  <a href="{% url 'articles:index' %}">BACK</a>
{% endblock %}